Use webpack for the build step
NIAEFEUP/nitsig pull request #165
Opened 2024-03-19 14:11 UTC by ttoino

Closes #164.

This PR migrates the build step away from the current `build-script.js` and uses webpack instead. It's quite inspired by the config at [Refined Github](https://github.com/refined-github/refined-github/blob/main/webpack.config.ts), but adapted to our specific needs.

This also migrates our project to corepack and yarn modern, so developers must run `corepack enable` before running `yarn install`.

2024-04-08 21:06 UTC, thePeras commented
Could you write the new script (corepack enable) before yarn install in the README file?

2024-07-05 11:09 UTC, thePeras requested changes
When I make one change, it compiles, but keep repeating the compilation even If I don't touch the code source. Any idea of what may be?

2024-07-05 18:20 UTC, thePeras commented
The problem I commented before is now solved!

The only problem here is the WebpackShellPluginNext scripts, which don't run when new changes are saved. However the CopyPlugin works fine.

2024-07-19 01:40 UTC, toni-santos approved these changes
It seems like Windows will still be a problem regarding watch scripts. :( However this is already a big improvement for the developer experience! Good job all :+1:

2024-07-19 13:08 UTC, thePeras approved these changes
✅ 🛫

2024-07-19 13:09 UTC, merged

2024-11-01 13:37 UTC, thePeras commented
@JaimeFRF Last time I work on this I notice the problem is the `CopyPlugin` is not being executing on changes, just at the start when you execute the watch script. You can check this by deleting the copied files after start yarn watch and change something. No file will be copied again.