Refactor javascript files and the popup
NIAEFEUP/nitsig pull request #199
Opened 2024-11-02 17:06 UTC by thePeras

Decided to refactor some little things 🤕 

Now the popup is this way. Hope you agree to the changes!

<img width="327" alt="Screenshot 2024-11-02 at 17 04 12" src="https://github.com/user-attachments/assets/c207dccd-fff2-4985-9693-8994c2dab8da">

What do you think to change the texts to?
- Barra de navegação
- Esconder atalhos
- Nova fonte de letra
- Relembrar sessão

2024-11-06 18:30 UTC, toni-santos requested changes
this is very good 🤩, we could start migrating some of these things to tsx. also what do you think about separating options further by page? it could be helpful as we increase customisation.

2024-11-06 18:30 UTC, toni-santos commented on content-scripts/modules/icons/index.ts
there are some parts of this file that could be reimplemented in jsx

2024-11-06 18:30 UTC, toni-santos commented on content-scripts/modules/options/addStyle.ts
> +    }
this could be tsx

2024-11-07 18:12 UTC, thePeras commented
> What do you think about separating options further by page? it could be helpful as we increase customisation.

I agree. I put a comment in the file, so when the options increase next time, could be an improvement

2024-11-07 18:24 UTC, toni-santos approved these changes

2024-11-07 18:24 UTC, merged